export const API_BASE_URL = 'http://localhost:8080';

export const symbolNames = {
        BTC: "Bitcoin",
        ETH: "Ethereum",
        USDT: "Tether",
        XRP: "XRP",
        BNB: "BNB",
        SOL: "Solana",
        USDC: "USD Coin",
        DOGE: "Dogecoin",
        TRX: "TRON",
        ADA: "Cardano",
        STETH: "Lido Staked Ether",
        HYPE: "Hyperliquid",
        WBTC: "Wrapped Bitcoin",
        WSTETH: "Wrapped stETH",
        SUI: "Sui",
        LINK: "Chainlink",
        AVAX: "Avalanche",
        XLM: "Stellar",
        BCH: "Bitcoin Cash",
        LEO: "LEO Token"
    };

export const defaultPairs = [
    "BTC/USD",
    "ETH/USD",
    "USDT/USD",
    "XRP/USD",
    "BNB/USD",
    "SOL/USD",
    "USDC/USD",
    "DOGE/USD",
    "TRX/USD",
    "ADA/USD",
    "STETH/USD",
    "HYPE/USD",
    "WBTC/USD",
    "WSTETH/USD",
    "SUI/USD",
    "LINK/USD",
    "AVAX/USD",
    "XLM/USD",
    "BCH/USD"];